openfoodfacts/power-user-script

OpenFoodFactsPower.user.js
Selected product images are not highlighted
=> Solve issue #17

OpenFoodFactsPower.user.js
=> hunger-games

OpenFoodFactsPower.user.js
Adds buttons for ingredients analysis and for moving a product to OBF to the list view.
=> Add buttons for Analysis and Move to OBF to the list view

OpenFoodFactsPower.user.js, README.md
=> add DuckDuckGo search link

OpenFoodFactsPower.user.js
=> detect product code on product view page, and stop the script dying on code.replace()

OpenFoodFactsPower.user.js
=> encode ingredients so they don't truncate at ; or &.

OpenFoodFactsPower.user.js
I keep losing track of which textareas I've changed...
=> list view - style save button if textarea has unsaved changes

OpenFoodFactsPower.user.js, README.md
Advanced search opportunities for mass edit
=> Advanced search opportunities for mass edit

OpenFoodFactsPower.user.js
currently it says "Saved!" even on failure.
=> list view ingredients edit - report save success/failure

OpenFoodFactsPower.user.js
- Use separate IDs for the timed alert messages, so they don't get mixed up if there's more than one.
- Add "Saving"->"Saved"/"Failed" mechanic to the "Moved" for OBF.
=> properly track multiple "Saving" messages, and notify failures moving to OBF

OpenFoodFactsPower.user.js
resolves #26
also
- refresh product view barcode code
- add help popup to list view
- some lint/whitespace tidying
- preparatory work for fetching list edit mode ingredients by product code instead of rerunning the search
=> Add graphical barcodes option to list view

OpenFoodFactsPower.user.js
so the browser spellchecks it in the right language.
=> add lang attribute on the ingredient OCR textarea

OpenFoodFactsPower.user.js, README.md
Should fix various tweaks to product list view broken when the tabbed results went live - direct edit links, showing barcodes, and mass-editing ingredients.
=> List view fixes

OpenFoodFactsPower.user.js
json only returns 24 results by default, when full page returns 100 now.
=> fix list view pagination

OpenFoodFactsPower.user.js
if you save and then move before the save status has faded out, the browser gets confused.
=> give save & move status divs different ids

.github/labeler.yml, .github/workflows/label.yml
=> ci: Label PRs automatically

.github/workflows/semantic-pr.yml
- ci: enforce semantic PRs
- generate changelogs
=> ci: enforce semantic PRs

OpenFoodFactsPower.user.js
=> fix: quick-fix-sidebar

OpenFoodFactsPower.user.js
Added localhost urls, to be able to use the power-user-script while making devs
=> feat: added localhost urls

OpenFoodFactsPower.user.js
Power user script allows to always display the barcode like suggested in #25. The chekbox appears in ? in list view.
=> feat: barcode display by default

OpenFoodFactsPower.user.js
add all flavors for local so that the script can be used for beauty, pet food, etc.
=> feat: add all flavors for local
